export const CHANGE_TEST_VALUE = "CHANGE_TEST_VALUE";

export const GET_POKEMON_REQUEST = "GET_POKEMON_REQUEST";
export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";
export const GET_POKEMON_FAILURE = "GET_POKEMON_FAILURE";

export const GET_INFO_POKEMON_REQUEST = "GET_INFO_POKEMON_REQUEST";
export const GET_INFO_POKEMON_SUCCESS = "GET_INFO_POKEMON_SUCCESS";
export const GET_INFO_POKEMON_FAILURE = "GET_INFO_POKEMON_FAILURE";

export const GET_POKEMON_ID_REQUEST = "GET_POKEMON_ID_REQUEST";
export const GET_POKEMON_ID_SUCCESS = "GET_POKEMON_ID_SUCCESS";
export const GET_POKEMON_ID_FAILURE = "GET_POKEMON_ID_FAILURE";
